### ISSUE TITLE
Support different suffixes for parquet files 

### ISSUE THREAD

**Issue by gschwend** [LSSTDESC/tables_io#61]
Please add `.parquet` and `.parq` to the list of valid file extensions for parquet files. 
These two options were used in DP0.1 and DP0.2 catalog files, respectively.

**Comment by gschwend** [comment]
@eacharles I can contribute with this piece of code. Just add me to this repo, if you agree, so I can assign the issue to myself.

**Comment by eacharles** [comment]
Hi Julia, 

You were already on the team, but only had write access, I upgraded that to “maintain” access to let you manage issues.

-e

**Comment by eacharles** [comment]
You are right, I added upgraded you on RAIL.  Ok, just did tables_io too.

-e

**Comment by gschwend** [comment]
Thanks!

**Comment by eacharles** [comment]
closed with #62

**Comment by hdante** [comment]
Hello, is it possible to reopen this issue ? I'm not being able to open files with the extensions ".parq" and ".parquet" because `read()`, a FileNotFoundError exception is thrown (but the file described in the exception message ends up with the ".pq" extension again):

```
>>> f = tables_io.read('objectTable_tract_3635_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_12_20220218T172932Z.parq')
Traceback (most recent call last):
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/tables_io/ioUtils.py", line 792, in readPqToDataFrames
    dataframes[key] = readPqToDataFrame(f"{basepath}{key}.pq")
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/tables_io/ioUtils.py", line 747, in readPqToDataFrame
    return pd.read_parquet(filepath, engine='pyarrow')
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 503, in read_parquet
    return impl.read(
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 244, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    handles = get_handle(
  File "/home/hdante/Trabalho/LineA/local/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'objectTable_tract_3635_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_12_20220218T172932Z.pq'

```

**Comment by gschwend** [comment]
Yes, I am going to take a look.

**Comment by eacharles** [comment]
I just confirmed that this is working within reason.

 (it will read pq and parq files as  pandas.core.frame.DataFrame and parquet files as pyarrow.lib.Table)

>>> import tables_io
>>> t = tables_io.read('test_outmd.pq')
column_list None
>>> type(t)
<class 'pandas.core.frame.DataFrame'>
>>> t = tables_io.read('test_outmd.parquet')
column_list None
>>> type(t)
<class 'pyarrow.lib.Table'>
>>> t = tables_io.read('test_outmd.parq')
column_list None
>>> type(t)
<class 'pandas.core.frame.DataFrame'>
